argo-cd:
  global:
    domain: "argocd.david-epa.nubes.stfc.ac.uk"

  server:
    ingress:
      ingressClassName: internal-nginx

stfc-cloud-longhorn:
  longhorn:
    ingress:
      ingressClassName: internal-nginx
      host: "longhorn.david-epa.nubes.stfc.ac.uk"
    persistence:
      # can't be set for RWX
      migratable: false

stfc-cloud-cert-manager:
  le-staging:
    enabled: true
    ingressClassName: ingress-nginx-external

  le-prod:
    email: cloud-support@stfc.ac.uk
    enabled: true
    ingressClassName: ingress-nginx-external

