{{- $clusterName := index .Values "stfc-cloud-opensearch" "opensearch-cluster" "cluster" "name" -}}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{$clusterName}}-ca-cert
  namespace: {{.Release.Namespace}}
spec:
  isCA: true
  commonName: {{$clusterName}}
  secretName: {{$clusterName}}-ca
  duration: 87600h # 10yr
  renewBefore: 8760h # 1yr
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  issuerRef:
    name: self-signed
    kind: ClusterIssuer
    group: cert-manager.io

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{$clusterName}}-ca-issuer
  namespace: {{.Release.Namespace}}
spec:
  ca:
    secretName: {{$clusterName}}-ca
