apiVersion: v2
name: cluster-api-addon-provider
version: 1.0.0
dependencies:
  - repository: https://azimuth-cloud.github.io/cluster-api-addon-provider
    name: cluster-api-addon-provider
    version: 0.7.1
