apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-deployed-apps
  namespace: argocd
spec:
  destination:
    namespace: {{ $.Values.global.namespace }}
    server: https://kubernetes.default.svc
  project: {{ $.Values.global.spec.project }}
  source:
    repoURL: {{ $.Values.global.spec.source.repoURL }}
    targetRevision: {{ default $.Values.global.spec.source.targetRevision $.Values.cloudDeployedApps.targetRevision }}
    path: charts/argocd-apps/
    helm:
      valueFiles:
        - ./values.yaml
        - ../../clusters/{{ $.Values.global.clusterName }}/app-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
---