{{- if .Values.infra -}}
{{- range $infra := .Values.infra -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  destination:
    namespace: {{ .namespace }}
    server: https://kubernetes.default.svc
  project: {{ $.Values.global.spec.project }}
  source:
    repoURL: {{ $.Values.global.spec.source.repoURL }}
    targetRevision: {{ default $.Values.global.spec.source.targetRevision .targetRevision }}
    path: charts/infra/{{ .chartName }}
    helm:
      valueFiles:
        {{- range $chartName, $paths := $.Values.valueFiles }}
        {{- if eq $chartName $infra.chartName }}
        {{- range $path := $paths }}
        - ../../../{{ $path }}
        {{- end }}
        {{- end }}
        {{- end }}

        {{- if .additionalValueFiles }}
        {{- range $path := .additionalValueFiles }}
        - ../../../{{ $path }}
        {{- end }}
        {{- end }}
  syncPolicy:
    {{- if not .disableAutomated }}
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    {{- end }}
    syncOptions:
      - CreateNamespace=true
---
{{- end }}
{{- end }}