argo-cd:
  global:
    domain: argocd.prod-worker.nubes.stfc.ac.uk

stfc-cloud-cert-manager:
  le-staging:
    enabled: true
    ingressClassName: ingress-nginx-external

  le-prod:
    email: cloud-support@stfc.ac.uk
    enabled: true
    ingressClassName: ingress-nginx-external