ingress-nginx-external:
  controller:
    config:
      annotations-risk-level: Critical
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    electionID: external-ingress-controller-leader
    ingressClass: ingress-nginx-external
    ingressClassResource:
      name: ingress-nginx-external
      enabled: true
      default: false
      controllerValue: "k8s.io/ingress-nginx-external"
    service:
      annotations:
        # Don't delete the floating ip when deleting loadbalancers
        # prevents errors when deleting clusters, leave as true
        loadbalancer.openstack.org/keep-floatingip: true
      loadBalancerIP: "130.246.80.218"
    allowSnippetAnnotations: true
