openstack-cluster:
  # Default values applied to all clusters unless override supersedes it

  addons:

    openstack:
      csiCinder:
        defaultStorageClass:
          availabilityZone: ceph
    
    ingress:
      enabled: true 
      nginx:
        release:
          values:
            service:
              loadBalancerIP:

            # need this for argocd ingress to work
            controller:
              extraArgs:
                enable-ssl-passthrough: true

  nodeGroups:
    - name: default-md-0
      machineCount: 2

  nodeGroupDefaults:
    nodeLabels:
      longhorn.store.nodeselect/longhorn-storage-node: true
    autoscale: false
    machineFlavor: l3.micro

    healthCheck:
      enabled: true
      spec:
        maxUnhealthy: 100%
        nodeStartupTimeout: 10m0s
        unhealthyConditions:
          - type: Ready
            status: Unknown
            timeout: 5m0s
          - type: Ready
            status: "False"
            timeout: 5m0s
  
  additionalPackages: []

  controlPlane:
    remediationStrategy:
      retryPeriod: 20m0s
      minHealthyPeriod: 1h0m0s

    machineCount: 5
    machineFlavor: l3.nano

  kubernetesVersion: "1.28.7"
  machineImage: "capi-ubuntu-2004-kube-v1.28.7-2024-03-01"

  registryAuth:
    {}

  machineSSHKeyName: