name: Promote Staging Helm Chart Versions to Prod

on:
  schedule:
    - cron: '0 12 * * 3'  # Wednesday at 12pm UTC
  workflow_dispatch:

env:
  author: "${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>"
  committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: "Setup Github Token"
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Check for changes
        id: check-changes
        run: |
          if diff -r charts/staging charts/prod > /dev/null; then
            echo "changes-detected=false" >> $GITHUB_OUTPUT
          else
            echo "changes-detected=true" >> $GITHUB_OUTPUT
          fi
  
      - name: Promote Changes
        if: steps.check-changes.outputs.changes-detected == 'true'
        run: |
          rm -rf charts/prod
          cp -r charts/staging charts/prod

      - name: Log no changes
        if: steps.check-changes.outputs.changes-detected == 'false'
        run: echo "No changes detected between staging and prod. Skipping PR creation."

      - name: Get current date
        if: steps.check-changes.outputs.changes-detected == 'true'
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Set branch and PR names
        if: steps.check-changes.outputs.changes-detected == 'true'
        id: env-vars
        run: |
          echo "pr_title=Promote Staging to Prod - ${{ steps.date.outputs.date }}" >> $GITHUB_OUTPUT

      - name: Commit and Create Pull Request
        if: steps.check-changes.outputs.changes-detected == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: "${{ steps.env-vars.outputs.pr_title }}"
          author: ${{ env.author }}
          committer: ${{ env.committer }}
          branch: promote-staging-to-prod
          delete-branch: true
          title: ${{ steps.env-vars.outputs.pr_title }}
          body: |
            Automated promotion PR to copy contents from `staging` to `prod`.
            
            This PR was automatically created by the environment promotion workflow.
          base: main
          labels: |
            automated
            environment-promotion
